//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Application boot failed 的本地化字符串。
        /// </summary>
        public static string AppBootFailed {
            get {
                return ResourceManager.GetString("AppBootFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applications can only run within the MSIX container. 的本地化字符串。
        /// </summary>
        public static string AppBootFailedContent1 {
            get {
                return ResourceManager.GetString("AppBootFailedContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. Check whether your application is correctly installed in the system. 的本地化字符串。
        /// </summary>
        public static string AppBootFailedContent2 {
            get {
                return ResourceManager.GetString("AppBootFailedContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. Check whether your application starts from the Start screen. 的本地化字符串。
        /// </summary>
        public static string AppBootFailedContent3 {
            get {
                return ResourceManager.GetString("AppBootFailedContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileRenamer 的本地化字符串。
        /// </summary>
        public static string AppDisplayName {
            get {
                return ResourceManager.GetString("AppDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Have you forgot to initialize app&apos;s resources? 的本地化字符串。
        /// </summary>
        public static string ResourcesInitializeFailed {
            get {
                return ResourceManager.GetString("ResourcesInitializeFailed", resourceCulture);
            }
        }
    }
}
