namespace FileRenamer
{
    [bindable]
    [default_interface]
    runtimeclass ReferenceKeyValuePairModel 
    {
        //ReferenceKeyValuePairModel();
        ReferenceKeyValuePairModel(String Key,String Value);
        
        String Key{ get; set; };
        String Value{ get; set; };
    }
}
