namespace FileRenamer
{
    [bindable]
    [default_interface]
    runtimeclass ThanksKeyValuePairModel 
    {
        ThanksKeyValuePairModel(String Key,String Value);
        
        String Key{ get; set; };
        String Value{ get; set; };
    }
}
