namespace PowerTools.Extensions.DataType.Enums
{
    public enum OperationKind
    {
        AddDriverAllSuccessfully = 0,
        AddDriverFailed = 1,
        AddDriverPartialSuccessfully = 2,
        AddInstallDriverAllSuccessfully = 3,
        AddInstallDriverFailed = 4,
        AddInstallDriverPartialSuccessfully = 5,
        CleanUpdateHistory = 6,
        CheckUpdate = 7,
        ContextMenuUpdate = 8,
        DeleteDriverAllSuccessfully = 9,
        DeleteDriverFailed = 10,
        DeleteDriverPartialSuccessfully = 11,
        DeleteDriverSuccessfully = 12,
        DeleteFileFailed = 13,
        Desktop = 14,
        File = 15,
        FileLost = 16,
        ForceDeleteDriverAllSuccessfully = 17,
        ForceDeleteDriverFailed = 18,
        ForceDeleteDriverPartialSuccessfully = 19,
        ForceDeleteDriverSuccessfully = 20,
        IconExtract = 21,
        InsiderPreviewSettings = 22,
        LanguageChange = 23,
        ListEmpty = 24,
        LogClean = 25,
        LoopbackSetResult = 26,
        MenuDarkThemeIconPathEmpty = 27,
        MenuDefaultIconPathEmpty = 28,
        MenuLightThemeIconPathEmpty = 29,
        MenuProgramPathEmpty = 30,
        MenuMatchRuleEmpty = 31,
        MenuTitleEmpty = 32,
        NoOperation = 33,
        SelectDriverEmpty = 34,
        ShellMenuNeedToRefreshData = 35,
        StartScreen = 36,
        Taskbar = 37,
        TerminateProcess = 38,
        ThemeChangeSameTime = 39,
        ThemeSwitchSaveResult = 40,
        ThemeSwitchRestoreResult = 41,
    }
}
