import "ViewModels\Pages\AboutViewModel.idl";

namespace FileRenamer
{
    [default_interface]
    runtimeclass AboutPage : Windows.UI.Xaml.Controls.Page
    {
        AboutPage();

        AboutViewModel ViewModel{ get; };

        String BriefIntroduction{ get; };
        String CreateDesktopShortcut{ get; };
        String CreateDesktopShortcutToolTip{ get; };
        String PinToStartScreen{ get; };
        String PinToStartScreenToolTip{ get; };
        String PinToTaskbar{ get; };
        String PinToTaskbarToolTip{ get; };
        String Precaution{ get; };
        String QuickOperation{ get; };
        String Reference{ get; };
        String ReferenceTitle{ get; };
        String SettingsHelp{ get; };
        String ShowLicense{ get; };
        String ShowLicenseToolTip{ get; };
        String ShowReleaseNotes{ get; };
        String ShowReleaseNotesToolTip{ get; };
        String Thanks{ get; };
        String ThanksTitle{ get; };
        String Title{ get; };
        String UpdateAndLicensing{ get; };
        String UseInstruction{ get; };
    }
}
