namespace FileRenamer
{
    [default_interface]
    runtimeclass IntroductionControl : Windows.UI.Xaml.Controls.UserControl
    {
        IntroductionControl();
        
        String BriefIntroduction{ get; };
    }
}
