// Copyright (c) Microsoft Corporation and Contributors.
// Licensed under the MIT License.
import "ViewModels\Window\MainWindowViewModel.idl";

namespace FileRenamer
{
	runtimeclass MainWindow : Microsoft.UI.Xaml.Window
	{
		MainWindow();
		MainWindowViewModel ViewModel{ get; };
		Int32 MyProperty;
	}
}