import "ViewModels\Window\MainViewModel.idl";

namespace FileRenamer
{
    [default_interface]
    runtimeclass MainPage : Windows.UI.Xaml.Controls.Page
    {
        MainPage();

        MainViewModel ViewModel{ get; };
        
        String FileName{ get; };
        String ExtensionName{ get; };
        String UpperAndLowerCase{ get; };
        String FileProperties{ get; };
        String About{ get; };
    }
}
