namespace FileRenamer
{
    [default_interface]
    runtimeclass PrecautionControl : Windows.UI.Xaml.Controls.UserControl
    {
        PrecautionControl();
        
        String Precaution{ get; };
    }
}
