import "ViewModels\Pages\SettingsViewModel.idl";

namespace FileRenamer
{
    [default_interface]
    runtimeclass SettingsPage : Windows.UI.Xaml.Controls.Page
    {
        SettingsPage();

        SettingsViewModel ViewModel{ get; };

        String Title{ get; };
        String Appearance{ get; };
        String General{ get; };
        String Advanced{ get; };
        String RestartApp{ get; };
        String RestartAppToolTip{ get; };
    }
}
