import "ViewModels\Controls\About\ThanksViewModel.idl";

namespace FileRenamer
{
    [default_interface]
    runtimeclass ThanksControl : Windows.UI.Xaml.Controls.UserControl
    {
        ThanksControl();

        ThanksViewModel ViewModel{ get; };
        
        String ThanksTitle{ get; };
    }
}
