//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllTools {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllTools() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.AllTools", typeof(AllTools).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Driver manager 的本地化字符串。
        /// </summary>
        public static string DriverManager {
            get {
                return ResourceManager.GetString("DriverManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View and manage device driver software 的本地化字符串。
        /// </summary>
        public static string DriverManagerDescription {
            get {
                return ResourceManager.GetString("DriverManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension name 的本地化字符串。
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch change file (folder) extension names 的本地化字符串。
        /// </summary>
        public static string ExtensionNameDescription {
            get {
                return ResourceManager.GetString("ExtensionNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File tools 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File certificate 的本地化字符串。
        /// </summary>
        public static string FileCertificate {
            get {
                return ResourceManager.GetString("FileCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Performs operations on the certificate of the signed file 的本地化字符串。
        /// </summary>
        public static string FileCertificateDescription {
            get {
                return ResourceManager.GetString("FileCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch change file (folder) names 的本地化字符串。
        /// </summary>
        public static string FileNameDescription {
            get {
                return ResourceManager.GetString("FileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File properties 的本地化字符串。
        /// </summary>
        public static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch modify file (folder) properties 的本地化字符串。
        /// </summary>
        public static string FilePropertiesDescription {
            get {
                return ResourceManager.GetString("FilePropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon extract 的本地化字符串。
        /// </summary>
        public static string IconExtract {
            get {
                return ResourceManager.GetString("IconExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract the icon embedded in the file 的本地化字符串。
        /// </summary>
        public static string IconExtractDescription {
            get {
                return ResourceManager.GetString("IconExtractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaf 的本地化字符串。
        /// </summary>
        public static string Loaf {
            get {
                return ResourceManager.GetString("Loaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Take a break when you&apos;re not inspired 的本地化字符串。
        /// </summary>
        public static string LoafDescription {
            get {
                return ResourceManager.GetString("LoafDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization tools 的本地化字符串。
        /// </summary>
        public static string Personalize {
            get {
                return ResourceManager.GetString("Personalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pri extract 的本地化字符串。
        /// </summary>
        public static string PriExtract {
            get {
                return ResourceManager.GetString("PriExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract the resources contained in the package resource index file (Pri) 的本地化字符串。
        /// </summary>
        public static string PriExtractDescription {
            get {
                return ResourceManager.GetString("PriExtractDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relax tools 的本地化字符串。
        /// </summary>
        public static string Relaxation {
            get {
                return ResourceManager.GetString("Relaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource tools 的本地化字符串。
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom shell menu 的本地化字符串。
        /// </summary>
        public static string ShellMenu {
            get {
                return ResourceManager.GetString("ShellMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customize the Windows shell menu 的本地化字符串。
        /// </summary>
        public static string ShellMenuDescription {
            get {
                return ResourceManager.GetString("ShellMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System tools 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System information 的本地化字符串。
        /// </summary>
        public static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View detailed information about the current system 的本地化字符串。
        /// </summary>
        public static string SystemInfoDescription {
            get {
                return ResourceManager.GetString("SystemInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All tools 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update manager 的本地化字符串。
        /// </summary>
        public static string UpdateManager {
            get {
                return ResourceManager.GetString("UpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download and install operating system updates manually 的本地化字符串。
        /// </summary>
        public static string UpdateManagerDescription {
            get {
                return ResourceManager.GetString("UpdateManagerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upper and lower case page 的本地化字符串。
        /// </summary>
        public static string UpperAndLowerCase {
            get {
                return ResourceManager.GetString("UpperAndLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Batch change the upper and lower case names of files (folders) 的本地化字符串。
        /// </summary>
        public static string UpperAndLowerCaseDescription {
            get {
                return ResourceManager.GetString("UpperAndLowerCaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System assessment 的本地化字符串。
        /// </summary>
        public static string WinSAT {
            get {
                return ResourceManager.GetString("WinSAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Benchmarking using system evaluation tools 的本地化字符串。
        /// </summary>
        public static string WinSATDescription {
            get {
                return ResourceManager.GetString("WinSATDescription", resourceCulture);
            }
        }
    }
}
