//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodeScanner {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeScanner() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.CodeScanner", typeof(CodeScanner).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Bar code 的本地化字符串。
        /// </summary>
        public static string BarCode {
            get {
                return ResourceManager.GetString("BarCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear recognize text 的本地化字符串。
        /// </summary>
        public static string ClearRecognizeText {
            get {
                return ResourceManager.GetString("ClearRecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and drop to the Code Scanner page 的本地化字符串。
        /// </summary>
        public static string DragOverContent {
            get {
                return ResourceManager.GetString("DragOverContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNG photo(*.png)|*.png|JPG photo(*.jpg)|*.jpg|PNG photo(*.png)|*.png 的本地化字符串。
        /// </summary>
        public static string FilterCondition {
            get {
                return ResourceManager.GetString("FilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate 的本地化字符串。
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate code 的本地化字符串。
        /// </summary>
        public static string GenerateCode {
            get {
                return ResourceManager.GetString("GenerateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type of the generated code 的本地化字符串。
        /// </summary>
        public static string GenerateCodeType {
            get {
                return ResourceManager.GetString("GenerateCodeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input generate text 的本地化字符串。
        /// </summary>
        public static string GenerateInputText {
            get {
                return ResourceManager.GetString("GenerateInputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate options 的本地化字符串。
        /// </summary>
        public static string GenerateOptions {
            get {
                return ResourceManager.GetString("GenerateOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Generate photo 的本地化字符串。
        /// </summary>
        public static string GeneratePhoto {
            get {
                return ResourceManager.GetString("GeneratePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether the picture is square 的本地化字符串。
        /// </summary>
        public static string IsPhotoSquare {
            get {
                return ResourceManager.GetString("IsPhotoSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string IsPhotoSquareOffContent {
            get {
                return ResourceManager.GetString("IsPhotoSquareOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string IsPhotoSquareOnContent {
            get {
                return ResourceManager.GetString("IsPhotoSquareOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not select multiple files 的本地化字符串。
        /// </summary>
        public static string NoMultiFile {
            get {
                return ResourceManager.GetString("NoMultiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open photo 的本地化字符串。
        /// </summary>
        public static string OpenPhoto {
            get {
                return ResourceManager.GetString("OpenPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parse 的本地化字符串。
        /// </summary>
        public static string Parse {
            get {
                return ResourceManager.GetString("Parse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo height 的本地化字符串。
        /// </summary>
        public static string PhotoHeight {
            get {
                return ResourceManager.GetString("PhotoHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Photo width 的本地化字符串。
        /// </summary>
        public static string PhotoWidth {
            get {
                return ResourceManager.GetString("PhotoWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print photo 的本地化字符串。
        /// </summary>
        public static string PrintPhoto {
            get {
                return ResourceManager.GetString("PrintPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QR code 的本地化字符串。
        /// </summary>
        public static string QRCode {
            get {
                return ResourceManager.GetString("QRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Read clipboard photo 的本地化字符串。
        /// </summary>
        public static string ReadClipboardPhoto {
            get {
                return ResourceManager.GetString("ReadClipboardPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recognized text 的本地化字符串。
        /// </summary>
        public static string RecognizeText {
            get {
                return ResourceManager.GetString("RecognizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Keep the bottom number of the barcode 的本地化字符串。
        /// </summary>
        public static string ReserveBarCodeText {
            get {
                return ResourceManager.GetString("ReserveBarCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string ReserveBarCodeTextOffContent {
            get {
                return ResourceManager.GetString("ReserveBarCodeTextOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string ReserveBarCodeTextOnContent {
            get {
                return ResourceManager.GetString("ReserveBarCodeTextOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save photo 的本地化字符串。
        /// </summary>
        public static string SavePhoto {
            get {
                return ResourceManager.GetString("SavePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select file 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1. The content of the generated bar code can only be composed of numbers or letters 的本地化字符串。
        /// </summary>
        public static string TipContent1 {
            get {
                return ResourceManager.GetString("TipContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tips 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code scanner 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
