//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 App information 的本地化字符串。
        /// </summary>
        public static string AppInformationTitle {
            get {
                return ResourceManager.GetString("AppInformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowsTools 的本地化字符串。
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application is running 的本地化字符串。
        /// </summary>
        public static string AppRunning {
            get {
                return ResourceManager.GetString("AppRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel download 的本地化字符串。
        /// </summary>
        public static string CancelDownload {
            get {
                return ResourceManager.GetString("CancelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close dialog 的本地化字符串。
        /// </summary>
        public static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all information 的本地化字符串。
        /// </summary>
        public static string CopyAll {
            get {
                return ResourceManager.GetString("CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy app information 的本地化字符串。
        /// </summary>
        public static string CopyAppInformation {
            get {
                return ResourceManager.GetString("CopyAppInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete and redownload 的本地化字符串。
        /// </summary>
        public static string DeleteAndRedownload {
            get {
                return ResourceManager.GetString("DeleteAndRedownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 .NET Framework version: 的本地化字符串。
        /// </summary>
        public static string DoNetVersion {
            get {
                return ResourceManager.GetString("DoNetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error code 的本地化字符串。
        /// </summary>
        public static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error message 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception code（HResult）: 的本地化字符串。
        /// </summary>
        public static string ExceptionCode {
            get {
                return ResourceManager.GetString("ExceptionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exception message: 的本地化字符串。
        /// </summary>
        public static string ExceptionMessage {
            get {
                return ResourceManager.GetString("ExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File check prompt 的本地化字符串。
        /// </summary>
        public static string FileCheckExist {
            get {
                return ResourceManager.GetString("FileCheckExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application has detected that the file you are about to download already exists. Do you hope? 的本地化字符串。
        /// </summary>
        public static string FileCheckExistContent {
            get {
                return ResourceManager.GetString("FileCheckExistContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name: 的本地化字符串。
        /// </summary>
        public static string FileNameCopy {
            get {
                return ResourceManager.GetString("FileNameCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path: 的本地化字符串。
        /// </summary>
        public static string FilePathCopy {
            get {
                return ResourceManager.GetString("FilePathCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowsTools License 的本地化字符串。
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mile Xaml version: 的本地化字符串。
        /// </summary>
        public static string MileXamlVersion {
            get {
                return ResourceManager.GetString("MileXamlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open folder 的本地化字符串。
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error message list 的本地化字符串。
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application restart 的本地化字符串。
        /// </summary>
        public static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app is about to restart, after the restart the app&apos;s data will be lost, make sure that your work has been saved in its entirety 的本地化字符串。
        /// </summary>
        public static string RestartContent {
            get {
                return ResourceManager.GetString("RestartContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows App SDK version： 的本地化字符串。
        /// </summary>
        public static string WindowsAppSDKVersion {
            get {
                return ResourceManager.GetString("WindowsAppSDKVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows UI version: 的本地化字符串。
        /// </summary>
        public static string WindowsUIVersion {
            get {
                return ResourceManager.GetString("WindowsUIVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WinUI 2 Version: 的本地化字符串。
        /// </summary>
        public static string WinUI2Version {
            get {
                return ResourceManager.GetString("WinUI2Version", resourceCulture);
            }
        }
    }
}
