//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExtractIcon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExtractIcon() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.ExtractIcon", typeof(ExtractIcon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Export all icons 的本地化字符串。
        /// </summary>
        public static string ExportAllIcons {
            get {
                return ResourceManager.GetString("ExportAllIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export selected icons 的本地化字符串。
        /// </summary>
        public static string ExportSelectedIcons {
            get {
                return ResourceManager.GetString("ExportSelectedIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Got {1} icons from file {0} 的本地化字符串。
        /// </summary>
        public static string GetResults {
            get {
                return ResourceManager.GetString("GetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No preview icon resources 的本地化字符串。
        /// </summary>
        public static string NoPreviewResources {
            get {
                return ResourceManager.GetString("NoPreviewResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File {0} does not have any icon resources 的本地化字符串。
        /// </summary>
        public static string NoResources {
            get {
                return ResourceManager.GetString("NoResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save icon format 的本地化字符串。
        /// </summary>
        public static string SaveIconFormat {
            get {
                return ResourceManager.GetString("SaveIconFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save icon size 的本地化字符串。
        /// </summary>
        public static string SaveIconSize {
            get {
                return ResourceManager.GetString("SaveIconSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select file 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract icon 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
