//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileName() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.FileName", typeof(FileName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auto 的本地化字符串。
        /// </summary>
        public static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;C&gt; Represent build date 的本地化字符串。
        /// </summary>
        public static string BuildDatePlaceHolder {
            get {
                return ResourceManager.GetString("BuildDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New file name 的本地化字符串。
        /// </summary>
        public static string ChangedName {
            get {
                return ResourceManager.GetString("ChangedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change the extension at the same time 的本地化字符串。
        /// </summary>
        public static string ChangeExtensionSimultaneously {
            get {
                return ResourceManager.GetString("ChangeExtensionSimultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name change rule:{0} 的本地化字符串。
        /// </summary>
        public static string ChangeRule {
            get {
                return ResourceManager.GetString("ChangeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The representative symbol can be placed anywhere, and the content can be customized before and after 的本地化字符串。
        /// </summary>
        public static string ChangeRuleDescription {
            get {
                return ResourceManager.GetString("ChangeRuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear list 的本地化字符串。
        /// </summary>
        public static string ClearList {
            get {
                return ResourceManager.GetString("ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy the file to the File Name page 的本地化字符串。
        /// </summary>
        public static string DragOverContent {
            get {
                return ResourceManager.GetString("DragOverContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no content 的本地化字符串。
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forward navigate 的本地化字符串。
        /// </summary>
        public static string ForwardNavigate {
            get {
                return ResourceManager.GetString("ForwardNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Look up 的本地化字符串。
        /// </summary>
        public static string LookUpString {
            get {
                return ResourceManager.GetString("LookUpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input look up content 的本地化字符串。
        /// </summary>
        public static string LookUpStringPlaceHolderText {
            get {
                return ResourceManager.GetString("LookUpStringPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;N&gt; Represent modify date 的本地化字符串。
        /// </summary>
        public static string ModifyDatePlaceHolder {
            get {
                return ResourceManager.GetString("ModifyDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying now,please wait...... 的本地化字符串。
        /// </summary>
        public static string ModifyingNow {
            get {
                return ResourceManager.GetString("ModifyingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My 1 file.jpg 的本地化字符串。
        /// </summary>
        public static string NameChangeList1ChangedName1 {
            get {
                return ResourceManager.GetString("NameChangeList1ChangedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My 2 file.TXT 的本地化字符串。
        /// </summary>
        public static string NameChangeList1ChangedName2 {
            get {
                return ResourceManager.GetString("NameChangeList1ChangedName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My 3 file.RAR 的本地化字符串。
        /// </summary>
        public static string NameChangeList1ChangedName3 {
            get {
                return ResourceManager.GetString("NameChangeList1ChangedName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My 4 file.GIF 的本地化字符串。
        /// </summary>
        public static string NameChangeList1ChangedName4 {
            get {
                return ResourceManager.GetString("NameChangeList1ChangedName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My UnNamed 1 file.jpg 的本地化字符串。
        /// </summary>
        public static string NameChangeList2ChangedName1 {
            get {
                return ResourceManager.GetString("NameChangeList2ChangedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My SN 2 file.TXT 的本地化字符串。
        /// </summary>
        public static string NameChangeList2ChangedName2 {
            get {
                return ResourceManager.GetString("NameChangeList2ChangedName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My TEST 3 file.RAR 的本地化字符串。
        /// </summary>
        public static string NameChangeList2ChangedName3 {
            get {
                return ResourceManager.GetString("NameChangeList2ChangedName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My C02_01_A 4 file.GIF 的本地化字符串。
        /// </summary>
        public static string NameChangeList2ChangedName4 {
            get {
                return ResourceManager.GetString("NameChangeList2ChangedName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1_picture.jpg 的本地化字符串。
        /// </summary>
        public static string NameChangeList3ChangedName1 {
            get {
                return ResourceManager.GetString("NameChangeList3ChangedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2_picture.TXT 的本地化字符串。
        /// </summary>
        public static string NameChangeList3ChangedName2 {
            get {
                return ResourceManager.GetString("NameChangeList3ChangedName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3_picture.RAR 的本地化字符串。
        /// </summary>
        public static string NameChangeList3ChangedName3 {
            get {
                return ResourceManager.GetString("NameChangeList3ChangedName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 4_picture.GIF 的本地化字符串。
        /// </summary>
        public static string NameChangeList3ChangedName4 {
            get {
                return ResourceManager.GetString("NameChangeList3ChangedName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My music (1).MP3 的本地化字符串。
        /// </summary>
        public static string NameChangeList4ChangedName1 {
            get {
                return ResourceManager.GetString("NameChangeList4ChangedName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My music (2).MP3 的本地化字符串。
        /// </summary>
        public static string NameChangeList4ChangedName2 {
            get {
                return ResourceManager.GetString("NameChangeList4ChangedName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My music (3).MP3 的本地化字符串。
        /// </summary>
        public static string NameChangeList4ChangedName3 {
            get {
                return ResourceManager.GetString("NameChangeList4ChangedName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My music (4).MP3 的本地化字符串。
        /// </summary>
        public static string NameChangeList4ChangedName4 {
            get {
                return ResourceManager.GetString("NameChangeList4ChangedName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnNamed.jpg 的本地化字符串。
        /// </summary>
        public static string NameChangeOriginalName1 {
            get {
                return ResourceManager.GetString("NameChangeOriginalName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SN.TXT 的本地化字符串。
        /// </summary>
        public static string NameChangeOriginalName2 {
            get {
                return ResourceManager.GetString("NameChangeOriginalName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TEST.RAR 的本地化字符串。
        /// </summary>
        public static string NameChangeOriginalName3 {
            get {
                return ResourceManager.GetString("NameChangeOriginalName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C02_01_A.GIF 的本地化字符串。
        /// </summary>
        public static string NameChangeOriginalName4 {
            get {
                return ResourceManager.GetString("NameChangeOriginalName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My &lt;#&gt; file 的本地化字符串。
        /// </summary>
        public static string NameChangeRule1 {
            get {
                return ResourceManager.GetString("NameChangeRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My &lt;&amp;&gt; &lt;#&gt; file 的本地化字符串。
        /// </summary>
        public static string NameChangeRule2 {
            get {
                return ResourceManager.GetString("NameChangeRule2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;#&gt;_picture 的本地化字符串。
        /// </summary>
        public static string NameChangeRule3 {
            get {
                return ResourceManager.GetString("NameChangeRule3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 My music (&lt;#&gt;),and change the extension name:MP3 的本地化字符串。
        /// </summary>
        public static string NameChangeRule4 {
            get {
                return ResourceManager.GetString("NameChangeRule4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name change example 的本地化字符串。
        /// </summary>
        public static string NameChangeTitle {
            get {
                return ResourceManager.GetString("NameChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New file (folder) name 的本地化字符串。
        /// </summary>
        public static string NewFileName {
            get {
                return ResourceManager.GetString("NewFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next navigate 的本地化字符串。
        /// </summary>
        public static string NextNavigate {
            get {
                return ResourceManager.GetString("NextNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial number format 的本地化字符串。
        /// </summary>
        public static string NumberFormat {
            get {
                return ResourceManager.GetString("NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;#&gt; Represent number 的本地化字符串。
        /// </summary>
        public static string NumberPlaceHolder {
            get {
                return ResourceManager.GetString("NumberPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original file (folder) name 的本地化字符串。
        /// </summary>
        public static string OriginalFileName {
            get {
                return ResourceManager.GetString("OriginalFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Original file name 的本地化字符串。
        /// </summary>
        public static string OriginalName {
            get {
                return ResourceManager.GetString("OriginalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;&amp;&gt; Represent original file name 的本地化字符串。
        /// </summary>
        public static string OriginalNameChangeFileName {
            get {
                return ResourceManager.GetString("OriginalNameChangeFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Placeholder description 的本地化字符串。
        /// </summary>
        public static string PlaceHolderDescription {
            get {
                return ResourceManager.GetString("PlaceHolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reference sample 的本地化字符串。
        /// </summary>
        public static string ReferenceSample {
            get {
                return ResourceManager.GetString("ReferenceSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rename rule 的本地化字符串。
        /// </summary>
        public static string RenameRule {
            get {
                return ResourceManager.GetString("RenameRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input rename rule 的本地化字符串。
        /// </summary>
        public static string RenameRulePlaceHolderText {
            get {
                return ResourceManager.GetString("RenameRulePlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        public static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input replace content 的本地化字符串。
        /// </summary>
        public static string ReplaceStringPlaceHolderText {
            get {
                return ResourceManager.GetString("ReplaceStringPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select file 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select folder 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start number 的本地化字符串。
        /// </summary>
        public static string StartNumber {
            get {
                return ResourceManager.GetString("StartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input start number 的本地化字符串。
        /// </summary>
        public static string StartNumberPlaceHolderText {
            get {
                return ResourceManager.GetString("StartNumberPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;$&gt; Represent today date 的本地化字符串。
        /// </summary>
        public static string TodayDatePlaceHolder {
            get {
                return ResourceManager.GetString("TodayDatePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total：{0} 的本地化字符串。
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View error information 的本地化字符串。
        /// </summary>
        public static string ViewErrorInformation {
            get {
                return ResourceManager.GetString("ViewErrorInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View example name change 的本地化字符串。
        /// </summary>
        public static string ViewNameChangeExample {
            get {
                return ResourceManager.GetString("ViewNameChangeExample", resourceCulture);
            }
        }
    }
}
