//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FileUnlock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUnlock() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.FileUnlock", typeof(FileUnlock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and drop to see 的本地化字符串。
        /// </summary>
        public static string DragAndDrop {
            get {
                return ResourceManager.GetString("DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag and drop to see information about the processes that are using the current file 的本地化字符串。
        /// </summary>
        public static string DragAndDropDescription {
            get {
                return ResourceManager.GetString("DragAndDropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to File Unlock page 的本地化字符串。
        /// </summary>
        public static string DragOverContent {
            get {
                return ResourceManager.GetString("DragOverContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File {0} is not in use 的本地化字符串。
        /// </summary>
        public static string FileNotUse {
            get {
                return ResourceManager.GetString("FileNotUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not select multi files 的本地化字符串。
        /// </summary>
        public static string NoMultiFile {
            get {
                return ResourceManager.GetString("NoMultiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open local file 的本地化字符串。
        /// </summary>
        public static string OpenLocalFile {
            get {
                return ResourceManager.GetString("OpenLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to open local directory 的本地化字符串。
        /// </summary>
        public static string OpenLocalFolder {
            get {
                return ResourceManager.GetString("OpenLocalFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open task manager 的本地化字符串。
        /// </summary>
        public static string OpenTaskManager {
            get {
                return ResourceManager.GetString("OpenTaskManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to obtain the usage information of file {0} 的本地化字符串。
        /// </summary>
        public static string ParseFileFailed {
            get {
                return ResourceManager.GetString("ParseFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully to obtain the usage information of file {0} 的本地化字符串。
        /// </summary>
        public static string ParseFileSuccessfully {
            get {
                return ResourceManager.GetString("ParseFileSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parsing the usage of file {0}, please wait... 的本地化字符串。
        /// </summary>
        public static string ParsingFile {
            get {
                return ResourceManager.GetString("ParsingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process id : 的本地化字符串。
        /// </summary>
        public static string ProcessId {
            get {
                return ResourceManager.GetString("ProcessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process name : 的本地化字符串。
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process path : 的本地化字符串。
        /// </summary>
        public static string ProcessPath {
            get {
                return ResourceManager.GetString("ProcessPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process user name : 的本地化字符串。
        /// </summary>
        public static string ProcessUser {
            get {
                return ResourceManager.GetString("ProcessUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select file 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Terminate process 的本地化字符串。
        /// </summary>
        public static string TerminateProcess {
            get {
                return ResourceManager.GetString("TerminateProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File unlock 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Welcome to the file unlock tool 的本地化字符串。
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
