//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Loaf {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Loaf() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.Loaf", typeof(Loaf).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Block all keys 的本地化字符串。
        /// </summary>
        public static string BlockAllKeys {
            get {
                return ResourceManager.GetString("BlockAllKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string BlockAllKeysOffContent {
            get {
                return ResourceManager.GetString("BlockAllKeysOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string BlockAllKeysOnContent {
            get {
                return ResourceManager.GetString("BlockAllKeysOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration options 的本地化字符串。
        /// </summary>
        public static string ConfigOptions {
            get {
                return ResourceManager.GetString("ConfigOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open this page and you can try to relax for a few moments 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration time 的本地化字符串。
        /// </summary>
        public static string DurationTime {
            get {
                return ResourceManager.GetString("DurationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading daily Bing wallpaper... 的本地化字符串。
        /// </summary>
        public static string LoadingBingWallpaper {
            get {
                return ResourceManager.GetString("LoadingBingWallpaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Duration: {0} hours,{1} minutes 的本地化字符串。
        /// </summary>
        public static string LoafTimeToolTip {
            get {
                return ResourceManager.GetString("LoafTimeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to lock the screen automatically after the simulation update is complete 的本地化字符串。
        /// </summary>
        public static string LockScreenAutomaticly {
            get {
                return ResourceManager.GetString("LockScreenAutomaticly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string LockScreenAutomaticlyOffContent {
            get {
                return ResourceManager.GetString("LockScreenAutomaticlyOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string LockScreenAutomaticlyOnContent {
            get {
                return ResourceManager.GetString("LockScreenAutomaticlyOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start loaf 的本地化字符串。
        /// </summary>
        public static string StartLoaf {
            get {
                return ResourceManager.GetString("StartLoaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tips 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.After running the fish, you can press Esc to exit. 的本地化字符串。
        /// </summary>
        public static string TipsContent1 {
            get {
                return ResourceManager.GetString("TipsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2. When running fish, do not shield Ctrl + Alt + Del keys on the keyboard. 的本地化字符串。
        /// </summary>
        public static string TipsContent2 {
            get {
                return ResourceManager.GetString("TipsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaf 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Simulate the style of the update page 的本地化字符串。
        /// </summary>
        public static string UpdateStyle {
            get {
                return ResourceManager.GetString("UpdateStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 10 style 的本地化字符串。
        /// </summary>
        public static string Windows10Style {
            get {
                return ResourceManager.GetString("Windows10Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 11 style 的本地化字符串。
        /// </summary>
        public static string Windows11Style {
            get {
                return ResourceManager.GetString("Windows11Style", resourceCulture);
            }
        }
    }
}
