//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoopbackManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoopbackManager() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.LoopbackManager", typeof(LoopbackManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 App binaries path 的本地化字符串。
        /// </summary>
        public static string AppBinariesPath {
            get {
                return ResourceManager.GetString("AppBinariesPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App container name 的本地化字符串。
        /// </summary>
        public static string AppContainerName {
            get {
                return ResourceManager.GetString("AppContainerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App container SID 的本地化字符串。
        /// </summary>
        public static string AppContainerSID {
            get {
                return ResourceManager.GetString("AppContainerSID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App container user 的本地化字符串。
        /// </summary>
        public static string AppContainerUser {
            get {
                return ResourceManager.GetString("AppContainerUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device has no application 的本地化字符串。
        /// </summary>
        public static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn loopback 的本地化字符串。
        /// </summary>
        public static string LearnLoopback {
            get {
                return ResourceManager.GetString("LearnLoopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading network loopback information, please wait... 的本地化字符串。
        /// </summary>
        public static string LoadingLoopback {
            get {
                return ResourceManager.GetString("LoadingLoopback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open working directory 的本地化字符串。
        /// </summary>
        public static string OpenWorkingDirectoryToolTip {
            get {
                return ResourceManager.GetString("OpenWorkingDirectoryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search app name 的本地化字符串。
        /// </summary>
        public static string SearchAppNamePHText {
            get {
                return ResourceManager.GetString("SearchAppNamePHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No apps found 的本地化字符串。
        /// </summary>
        public static string SearchEmptyDescription {
            get {
                return ResourceManager.GetString("SearchEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string SelectedToolTip {
            get {
                return ResourceManager.GetString("SelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select none 的本地化字符串。
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loopback manager 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Unknown] 的本地化字符串。
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unselected 的本地化字符串。
        /// </summary>
        public static string UnSelectedToolTip {
            get {
                return ResourceManager.GetString("UnSelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Working directory 的本地化字符串。
        /// </summary>
        public static string WorkingDirectory {
            get {
                return ResourceManager.GetString("WorkingDirectory", resourceCulture);
            }
        }
    }
}
