//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.Notification", typeof(Notification).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The app information has been successfully copied to the clipboard 的本地化字符串。
        /// </summary>
        public static string AppInformationCopy {
            get {
                return ResourceManager.GetString("AppInformationCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The desktop shortcut for the app was created successfully 的本地化字符串。
        /// </summary>
        public static string DesktopShortcutSuccessfully {
            get {
                return ResourceManager.GetString("DesktopShortcutSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app&apos;s desktop shortcut failed to create, please create it manually 的本地化字符串。
        /// </summary>
        public static string DesktopShortFailed {
            get {
                return ResourceManager.GetString("DesktopShortFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The icon failed to be saved. Please check the access permission of the local directory 的本地化字符串。
        /// </summary>
        public static string IconExtractFailed {
            get {
                return ResourceManager.GetString("IconExtractFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The icon has been saved successfully 的本地化字符串。
        /// </summary>
        public static string IconExtractSuccessfully {
            get {
                return ResourceManager.GetString("IconExtractSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The language setting is modified successfully and takes effect after restarting the application 的本地化字符串。
        /// </summary>
        public static string LanguageChange {
            get {
                return ResourceManager.GetString("LanguageChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are no files in the list 的本地化字符串。
        /// </summary>
        public static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Log cleanup failed.You can manually turn on folder cleanup logging 的本地化字符串。
        /// </summary>
        public static string LogCleanFailed {
            get {
                return ResourceManager.GetString("LogCleanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All log records were cleaned up successfully 的本地化字符串。
        /// </summary>
        public static string LogCleanSuccessfully {
            get {
                return ResourceManager.GetString("LogCleanSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please select at least one option or enter the content before proceeding 的本地化字符串。
        /// </summary>
        public static string NoOperation {
            get {
                return ResourceManager.GetString("NoOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This error message has been successfully copied to the clipboard 的本地化字符串。
        /// </summary>
        public static string OperationFailedCopy {
            get {
                return ResourceManager.GetString("OperationFailedCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The {0} error message was successfully copied to the clipboard 的本地化字符串。
        /// </summary>
        public static string OperationFailedSelectedCopy {
            get {
                return ResourceManager.GetString("OperationFailedSelectedCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files in the list were modified successfully, and {1} files failed to be modified 的本地化字符串。
        /// </summary>
        public static string OperationResultFailed {
            get {
                return ResourceManager.GetString("OperationResultFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} files in the list are modified successfully 的本地化字符串。
        /// </summary>
        public static string OperationResultSuccessfully {
            get {
                return ResourceManager.GetString("OperationResultSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App pinning to Start screen failed, please pin it manually 的本地化字符串。
        /// </summary>
        public static string StartScreenFailed {
            get {
                return ResourceManager.GetString("StartScreenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You successfully pinned the app to the Start screen 的本地化字符串。
        /// </summary>
        public static string StartScreenSuccessfully {
            get {
                return ResourceManager.GetString("StartScreenSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 App pinning to taskbar failed. Please pin manually 的本地化字符串。
        /// </summary>
        public static string TaskbarFailed {
            get {
                return ResourceManager.GetString("TaskbarFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The app was successfully pinned to the taskbar 的本地化字符串。
        /// </summary>
        public static string TaskbarSuccessfully {
            get {
                return ResourceManager.GetString("TaskbarSuccessfully", resourceCulture);
            }
        }
    }
}
