//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PriExtract {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PriExtract() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.PriExtract", typeof(PriExtract).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Absolute path 的本地化字符串。
        /// </summary>
        public static string AbsolutePath {
            get {
                return ResourceManager.GetString("AbsolutePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content 的本地化字符串。
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all file path 的本地化字符串。
        /// </summary>
        public static string CopyAllFilePath {
            get {
                return ResourceManager.GetString("CopyAllFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy all string 的本地化字符串。
        /// </summary>
        public static string CopyAllString {
            get {
                return ResourceManager.GetString("CopyAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy selected file path 的本地化字符串。
        /// </summary>
        public static string CopySelectedFilePath {
            get {
                return ResourceManager.GetString("CopySelectedFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy selected string 的本地化字符串。
        /// </summary>
        public static string CopySelectedString {
            get {
                return ResourceManager.GetString("CopySelectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add to the Pri Extract page 的本地化字符串。
        /// </summary>
        public static string DragOverContent {
            get {
                return ResourceManager.GetString("DragOverContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Embedded data 的本地化字符串。
        /// </summary>
        public static string EmbeddedData {
            get {
                return ResourceManager.GetString("EmbeddedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no content 的本地化字符串。
        /// </summary>
        public static string EmptyList {
            get {
                return ResourceManager.GetString("EmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export all embedded data 的本地化字符串。
        /// </summary>
        public static string ExportAllEmbeddedData {
            get {
                return ResourceManager.GetString("ExportAllEmbeddedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export selected embedded data 的本地化字符串。
        /// </summary>
        public static string ExportSelectedEmbeddedData {
            get {
                return ResourceManager.GetString("ExportSelectedEmbeddedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract 的本地化字符串。
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extract options 的本地化字符串。
        /// </summary>
        public static string ExtractOptions {
            get {
                return ResourceManager.GetString("ExtractOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the extracted embedded data 的本地化字符串。
        /// </summary>
        public static string ExtractSaveEmbeddedData {
            get {
                return ResourceManager.GetString("ExtractSaveEmbeddedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the extracted file path 的本地化字符串。
        /// </summary>
        public static string ExtractSaveFilePath {
            get {
                return ResourceManager.GetString("ExtractSaveFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save while extracting 的本地化字符串。
        /// </summary>
        public static string ExtractSaveSamely {
            get {
                return ResourceManager.GetString("ExtractSaveSamely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save the extracted string 的本地化字符串。
        /// </summary>
        public static string ExtractSaveString {
            get {
                return ResourceManager.GetString("ExtractSaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path 的本地化字符串。
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Package resources index(*.pri)|*.pri 的本地化字符串。
        /// </summary>
        public static string FilterCondition {
            get {
                return ResourceManager.GetString("FilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Get {1} datas from file {0} 的本地化字符串。
        /// </summary>
        public static string GetResults {
            get {
                return ResourceManager.GetString("GetResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If not inputed, the system default language is used 的本地化字符串。
        /// </summary>
        public static string InputLanguageToolTip {
            get {
                return ResourceManager.GetString("InputLanguageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key 的本地化字符串。
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not select multiple files 的本地化字符串。
        /// </summary>
        public static string NoMultiFile {
            get {
                return ResourceManager.GetString("NoMultiFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only files with extensions &quot;.pri&quot; are allowed 的本地化字符串。
        /// </summary>
        public static string NoOtherExtensionNameFile {
            get {
                return ResourceManager.GetString("NoOtherExtensionNameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No file is selected 的本地化字符串。
        /// </summary>
        public static string NoSelectedFile {
            get {
                return ResourceManager.GetString("NoSelectedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Optional:Input language 的本地化字符串。
        /// </summary>
        public static string PlaceHolderText {
            get {
                return ResourceManager.GetString("PlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processing now 的本地化字符串。
        /// </summary>
        public static string ProcessingNow {
            get {
                return ResourceManager.GetString("ProcessingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to select all or deselect 的本地化字符串。
        /// </summary>
        public static string SelectDescription {
            get {
                return ResourceManager.GetString("SelectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected folder: {0} 的本地化字符串。
        /// </summary>
        public static string SelectedFolder {
            get {
                return ResourceManager.GetString("SelectedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected 的本地化字符串。
        /// </summary>
        public static string SelectedToolTip {
            get {
                return ResourceManager.GetString("SelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select file 的本地化字符串。
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select folder 的本地化字符串。
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select save folder 的本地化字符串。
        /// </summary>
        public static string SelectSaveFolder {
            get {
                return ResourceManager.GetString("SelectSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String 的本地化字符串。
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pri extract 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnSelected 的本地化字符串。
        /// </summary>
        public static string UnSelectedToolTip {
            get {
                return ResourceManager.GetString("UnSelectedToolTip", resourceCulture);
            }
        }
    }
}
