//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShellMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellMenu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.ShellMenu", typeof(ShellMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add menu 的本地化字符串。
        /// </summary>
        public static string AddMenu {
            get {
                return ResourceManager.GetString("AddMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply modify 的本地化字符串。
        /// </summary>
        public static string ApplyModify {
            get {
                return ResourceManager.GetString("ApplyModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu list 的本地化字符串。
        /// </summary>
        public static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return default 的本地化字符串。
        /// </summary>
        public static string ReturnDefault {
            get {
                return ResourceManager.GetString("ReturnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu icon 的本地化字符串。
        /// </summary>
        public static string RootMenuIcon {
            get {
                return ResourceManager.GetString("RootMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu name 的本地化字符串。
        /// </summary>
        public static string RootMenuName {
            get {
                return ResourceManager.GetString("RootMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu settings 的本地化字符串。
        /// </summary>
        public static string RootMenuSettings {
            get {
                return ResourceManager.GetString("RootMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom shell menu 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
