//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShellMenu {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShellMenu() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.ShellMenu", typeof(ShellMenu).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add menu item 的本地化字符串。
        /// </summary>
        public static string AddMenuItem {
            get {
                return ResourceManager.GetString("AddMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Apply 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear menu items 的本地化字符串。
        /// </summary>
        public static string ClearMenu {
            get {
                return ResourceManager.GetString("ClearMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear all custom menu items 的本地化字符串。
        /// </summary>
        public static string ClearMenuToolTip {
            get {
                return ResourceManager.GetString("ClearMenuToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark theme icon 的本地化字符串。
        /// </summary>
        public static string DarkThemeIcon {
            get {
                return ResourceManager.GetString("DarkThemeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default icon 的本地化字符串。
        /// </summary>
        public static string DefaultIcon {
            get {
                return ResourceManager.GetString("DefaultIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows tools 的本地化字符串。
        /// </summary>
        public static string DefaultRootText {
            get {
                return ResourceManager.GetString("DefaultRootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s no menu items 的本地化字符串。
        /// </summary>
        public static string EmptyDescription {
            get {
                return ResourceManager.GetString("EmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon file(*.ico)|*.ico 的本地化字符串。
        /// </summary>
        public static string FilterCondition {
            get {
                return ResourceManager.GetString("FilterCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First level menu 的本地化字符串。
        /// </summary>
        public static string FirstLevelMenu {
            get {
                return ResourceManager.GetString("FirstLevelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light theme icon 的本地化字符串。
        /// </summary>
        public static string LightThemeIcon {
            get {
                return ResourceManager.GetString("LightThemeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu icon 的本地化字符串。
        /// </summary>
        public static string MenuIcon {
            get {
                return ResourceManager.GetString("MenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu icon path: 的本地化字符串。
        /// </summary>
        public static string MenuIconToolTip {
            get {
                return ResourceManager.GetString("MenuIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu list 的本地化字符串。
        /// </summary>
        public static string MenuList {
            get {
                return ResourceManager.GetString("MenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu order 的本地化字符串。
        /// </summary>
        public static string MenuOrder {
            get {
                return ResourceManager.GetString("MenuOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program file path 的本地化字符串。
        /// </summary>
        public static string MenuProgramPath {
            get {
                return ResourceManager.GetString("MenuProgramPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The application path is not set 的本地化字符串。
        /// </summary>
        public static string MenuProgramPathPHText {
            get {
                return ResourceManager.GetString("MenuProgramPathPHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu program path:  的本地化字符串。
        /// </summary>
        public static string MenuProgramPathToolTip {
            get {
                return ResourceManager.GetString("MenuProgramPathToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu settings 的本地化字符串。
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu title 的本地化字符串。
        /// </summary>
        public static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please input the menu title 的本地化字符串。
        /// </summary>
        public static string MenuTitlePHText {
            get {
                return ResourceManager.GetString("MenuTitlePHText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Menu title:  的本地化字符串。
        /// </summary>
        public static string MenuTitleToolTip {
            get {
                return ResourceManager.GetString("MenuTitleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify 的本地化字符串。
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Precautions 的本地化字符串。
        /// </summary>
        public static string Precautions {
            get {
                return ResourceManager.GetString("Precautions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.The submenu level is only supported up to the secondary menu 的本地化字符串。
        /// </summary>
        public static string PrecautionsContent1 {
            get {
                return ResourceManager.GetString("PrecautionsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.After the menu content is updated, there may be a delay. Please open it after a period of time 的本地化字符串。
        /// </summary>
        public static string PrecautionsContent2 {
            get {
                return ResourceManager.GetString("PrecautionsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3. It is recommended to avoid too many secondary menus, because this may lead to a long menu loading time, which will cause a deadlock. 的本地化字符串。
        /// </summary>
        public static string PrecautionsContent3 {
            get {
                return ResourceManager.GetString("PrecautionsContent3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return default 的本地化字符串。
        /// </summary>
        public static string ReturnDefault {
            get {
                return ResourceManager.GetString("ReturnDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu icon 的本地化字符串。
        /// </summary>
        public static string RootMenuIcon {
            get {
                return ResourceManager.GetString("RootMenuIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu name 的本地化字符串。
        /// </summary>
        public static string RootMenuName {
            get {
                return ResourceManager.GetString("RootMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Root menu settings 的本地化字符串。
        /// </summary>
        public static string RootMenuSettings {
            get {
                return ResourceManager.GetString("RootMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second level menu 的本地化字符串。
        /// </summary>
        public static string SecondLevelMenu {
            get {
                return ResourceManager.GetString("SecondLevelMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select icon 的本地化字符串。
        /// </summary>
        public static string SelectIcon {
            get {
                return ResourceManager.GetString("SelectIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to enable theme icon 的本地化字符串。
        /// </summary>
        public static string ShouldEnableThemeIcon {
            get {
                return ResourceManager.GetString("ShouldEnableThemeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string ShouldEnableThemeIconOffContent {
            get {
                return ResourceManager.GetString("ShouldEnableThemeIconOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string ShouldEnableThemeIconOnContent {
            get {
                return ResourceManager.GetString("ShouldEnableThemeIconOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 When turned on, you can set menu icon individually for light and dark themes 的本地化字符串。
        /// </summary>
        public static string ShouldEnableThemeIconToolTip {
            get {
                return ResourceManager.GetString("ShouldEnableThemeIconToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom shell menu 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The dark theme icon path is not set 的本地化字符串。
        /// </summary>
        public static string UnknownDarkThemeIconPath {
            get {
                return ResourceManager.GetString("UnknownDarkThemeIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The icon path is not set 的本地化字符串。
        /// </summary>
        public static string UnknownDefaultIconPath {
            get {
                return ResourceManager.GetString("UnknownDefaultIconPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The light theme icon path is not set 的本地化字符串。
        /// </summary>
        public static string UnknownLightThemeIconPath {
            get {
                return ResourceManager.GetString("UnknownLightThemeIconPath", resourceCulture);
            }
        }
    }
}
