//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SystemInfo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SystemInfo() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.SystemInfo", typeof(SystemInfo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Auxiliary tools 的本地化字符串。
        /// </summary>
        public static string AuxiliaryTool {
            get {
                return ResourceManager.GetString("AuxiliaryTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer management 的本地化字符串。
        /// </summary>
        public static string ComputerManagement {
            get {
                return ResourceManager.GetString("ComputerManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device specification 的本地化字符串。
        /// </summary>
        public static string DeviceInformation {
            get {
                return ResourceManager.GetString("DeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics 的本地化字符串。
        /// </summary>
        public static string GraphicsInformation {
            get {
                return ResourceManager.GetString("GraphicsInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Management console 的本地化字符串。
        /// </summary>
        public static string ManagementConsole {
            get {
                return ResourceManager.GetString("ManagementConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Network 的本地化字符串。
        /// </summary>
        public static string NetworkInformation {
            get {
                return ResourceManager.GetString("NetworkInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operating System 的本地化字符串。
        /// </summary>
        public static string OSInformation {
            get {
                return ResourceManager.GetString("OSInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registry editor 的本地化字符串。
        /// </summary>
        public static string RegistryEditor {
            get {
                return ResourceManager.GetString("RegistryEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Storage 的本地化字符串。
        /// </summary>
        public static string StorageInformation {
            get {
                return ResourceManager.GetString("StorageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System information 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
