//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UpdateManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UpdateManager() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.UpdateManager", typeof(UpdateManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Aborted 的本地化字符串。
        /// </summary>
        public static string Aborted {
            get {
                return ResourceManager.GetString("Aborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application ID 的本地化字符串。
        /// </summary>
        public static string ApplicationID {
            get {
                return ResourceManager.GetString("ApplicationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Available update 的本地化字符串。
        /// </summary>
        public static string AvailableUpdate {
            get {
                return ResourceManager.GetString("AvailableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Beta channel 的本地化字符串。
        /// </summary>
        public static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Canary channel 的本地化字符串。
        /// </summary>
        public static string Canary {
            get {
                return ResourceManager.GetString("Canary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chcek update 的本地化字符串。
        /// </summary>
        public static string ChcekUpdate {
            get {
                return ResourceManager.GetString("ChcekUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checking updates... 的本地化字符串。
        /// </summary>
        public static string CheckingUpdate {
            get {
                return ResourceManager.GetString("CheckingUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy update information 的本地化字符串。
        /// </summary>
        public static string CopyInformation {
            get {
                return ResourceManager.GetString("CopyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DCat Flighting Prod 的本地化字符串。
        /// </summary>
        public static string DCatFlightingProd {
            get {
                return ResourceManager.GetString("DCatFlightingProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update description 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dev channel 的本地化字符串。
        /// </summary>
        public static string Dev {
            get {
                return ResourceManager.GetString("Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do not enter 的本地化字符串。
        /// </summary>
        public static string DonotEnter {
            get {
                return ResourceManager.GetString("DonotEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows update does not include drivers 的本地化字符串。
        /// </summary>
        public static string ExcludeDrivers {
            get {
                return ResourceManager.GetString("ExcludeDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string ExcludeDriversOffContent {
            get {
                return ResourceManager.GetString("ExcludeDriversOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string ExcludeDriversOnContent {
            get {
                return ResourceManager.GetString("ExcludeDriversOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed 的本地化字符串。
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Force access to Windows insider program 的本地化字符串。
        /// </summary>
        public static string ForceAccessWIP {
            get {
                return ResourceManager.GetString("ForceAccessWIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hidden update 的本地化字符串。
        /// </summary>
        public static string HiddenUpdate {
            get {
                return ResourceManager.GetString("HiddenUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HIde 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide updates: Only in Administrator mode can hide updates 的本地化字符串。
        /// </summary>
        public static string HideUpdateToolTip {
            get {
                return ResourceManager.GetString("HideUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether the search results contain replaced updates 的本地化字符串。
        /// </summary>
        public static string IncludePotentiallySupersededUpdate {
            get {
                return ResourceManager.GetString("IncludePotentiallySupersededUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string IncludePotentiallySupersededUpdateOffContent {
            get {
                return ResourceManager.GetString("IncludePotentiallySupersededUpdateOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string IncludePotentiallySupersededUpdateOnContent {
            get {
                return ResourceManager.GetString("IncludePotentiallySupersededUpdateOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 In progress 的本地化字符串。
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Install 的本地化字符串。
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Installed update 的本地化字符串。
        /// </summary>
        public static string InstalledUpdate {
            get {
                return ResourceManager.GetString("InstalledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Microsoft update 的本地化字符串。
        /// </summary>
        public static string MicrosoftUpdate {
            get {
                return ResourceManager.GetString("MicrosoftUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No available update 的本地化字符串。
        /// </summary>
        public static string NoAvailableUpdate {
            get {
                return ResourceManager.GetString("NoAvailableUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No hidden update 的本地化字符串。
        /// </summary>
        public static string NoHiddenUpdate {
            get {
                return ResourceManager.GetString("NoHiddenUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No installed update 的本地化字符串。
        /// </summary>
        public static string NoInstalledUpdate {
            get {
                return ResourceManager.GetString("NoInstalledUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not started 的本地化字符串。
        /// </summary>
        public static string NotStarted {
            get {
                return ResourceManager.GetString("NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update history is empty 的本地化字符串。
        /// </summary>
        public static string NoUpdateHistory {
            get {
                return ResourceManager.GetString("NoUpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open support url 的本地化字符串。
        /// </summary>
        public static string OpenSupportUrl {
            get {
                return ResourceManager.GetString("OpenSupportUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation result 的本地化字符串。
        /// </summary>
        public static string OperationResult {
            get {
                return ResourceManager.GetString("OperationResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Release preview 的本地化字符串。
        /// </summary>
        public static string ReleasePreview {
            get {
                return ResourceManager.GetString("ReleasePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select 的本地化字符串。
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select all 的本地化字符串。
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select none 的本地化字符串。
        /// </summary>
        public static string SelectNone {
            get {
                return ResourceManager.GetString("SelectNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show updates: Only in Administrator mode can hide updates 的本地化字符串。
        /// </summary>
        public static string ShowUpdateToolTip {
            get {
                return ResourceManager.GetString("ShowUpdateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeeded 的本地化字符串。
        /// </summary>
        public static string Succeeded {
            get {
                return ResourceManager.GetString("Succeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Succeed with errors 的本地化字符串。
        /// </summary>
        public static string SucceedWithErrors {
            get {
                return ResourceManager.GetString("SucceedWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update manager 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Uninstall 的本地化字符串。
        /// </summary>
        public static string UnInstall {
            get {
                return ResourceManager.GetString("UnInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update configuration (run as administrator) 的本地化字符串。
        /// </summary>
        public static string UpdateConfiguration {
            get {
                return ResourceManager.GetString("UpdateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update history 的本地化字符串。
        /// </summary>
        public static string UpdateHistory {
            get {
                return ResourceManager.GetString("UpdateHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update name 的本地化字符串。
        /// </summary>
        public static string UpdateName {
            get {
                return ResourceManager.GetString("UpdateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update settings 的本地化字符串。
        /// </summary>
        public static string UpdateSettings {
            get {
                return ResourceManager.GetString("UpdateSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update source 的本地化字符串。
        /// </summary>
        public static string UpdateSource {
            get {
                return ResourceManager.GetString("UpdateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows store (DCat Prod) 的本地化字符串。
        /// </summary>
        public static string WindowsStore {
            get {
                return ResourceManager.GetString("WindowsStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows update 的本地化字符串。
        /// </summary>
        public static string WindowsUpdate {
            get {
                return ResourceManager.GetString("WindowsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WIP Settings 的本地化字符串。
        /// </summary>
        public static string WIPSettings {
            get {
                return ResourceManager.GetString("WIPSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open Windows insider preview settings 的本地化字符串。
        /// </summary>
        public static string WIPSettingsToolTip {
            get {
                return ResourceManager.GetString("WIPSettingsToolTip", resourceCulture);
            }
        }
    }
}
