//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Window {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Window() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.Window", typeof(Window).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All tools 的本地化字符串。
        /// </summary>
        public static string AllTools {
            get {
                return ResourceManager.GetString("AllTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WindowsTools 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download manager 的本地化字符串。
        /// </summary>
        public static string DownloadManager {
            get {
                return ResourceManager.GetString("DownloadManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Driver manager 的本地化字符串。
        /// </summary>
        public static string DriverManager {
            get {
                return ResourceManager.GetString("DriverManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension name 的本地化字符串。
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File tools 的本地化字符串。
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File certificate 的本地化字符串。
        /// </summary>
        public static string FileCertificate {
            get {
                return ResourceManager.GetString("FileCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File name 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File properties 的本地化字符串。
        /// </summary>
        public static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File unlock 的本地化字符串。
        /// </summary>
        public static string FileUnlock {
            get {
                return ResourceManager.GetString("FileUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon extract 的本地化字符串。
        /// </summary>
        public static string IconExtract {
            get {
                return ResourceManager.GetString("IconExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loaf 的本地化字符串。
        /// </summary>
        public static string Loaf {
            get {
                return ResourceManager.GetString("Loaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loopback manager 的本地化字符串。
        /// </summary>
        public static string LoopbackManager {
            get {
                return ResourceManager.GetString("LoopbackManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} navigation failed 的本地化字符串。
        /// </summary>
        public static string NavigationFailed {
            get {
                return ResourceManager.GetString("NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personalization tools 的本地化字符串。
        /// </summary>
        public static string Personalize {
            get {
                return ResourceManager.GetString("Personalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pri extract 的本地化字符串。
        /// </summary>
        public static string PriExtract {
            get {
                return ResourceManager.GetString("PriExtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Relax tools 的本地化字符串。
        /// </summary>
        public static string Relaxation {
            get {
                return ResourceManager.GetString("Relaxation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Resource tools 的本地化字符串。
        /// </summary>
        public static string Resource {
            get {
                return ResourceManager.GetString("Resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom shell menu 的本地化字符串。
        /// </summary>
        public static string ShellMenu {
            get {
                return ResourceManager.GetString("ShellMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System tools 的本地化字符串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System information 的本地化字符串。
        /// </summary>
        public static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update manager 的本地化字符串。
        /// </summary>
        public static string UpdateManager {
            get {
                return ResourceManager.GetString("UpdateManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upper and lower case 的本地化字符串。
        /// </summary>
        public static string UpperAndLowerCase {
            get {
                return ResourceManager.GetString("UpperAndLowerCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System assessment 的本地化字符串。
        /// </summary>
        public static string WinSAT {
            get {
                return ResourceManager.GetString("WinSAT", resourceCulture);
            }
        }
    }
}
