//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTools.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WinSAT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinSAT() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTools.Strings.WinSAT", typeof(WinSAT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Assessment items 的本地化字符串。
        /// </summary>
        public static string AssessmentItems {
            get {
                return ResourceManager.GetString("AssessmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Basic score 的本地化字符串。
        /// </summary>
        public static string BasicScore {
            get {
                return ResourceManager.GetString("BasicScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Component 的本地化字符串。
        /// </summary>
        public static string Component {
            get {
                return ResourceManager.GetString("Component", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Windows Experience Index evaluates major system components with scores ranging from 1.0 to 9.9 的本地化字符串。
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The Windows experience score has not been established 的本地化字符串。
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Gaming graphics 的本地化字符串。
        /// </summary>
        public static string GamingGraphics {
            get {
                return ResourceManager.GetString("GamingGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3D businesss and gaming graphics performance 的本地化字符串。
        /// </summary>
        public static string GamingGraphicsItem {
            get {
                return ResourceManager.GetString("GamingGraphicsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Graphics 的本地化字符串。
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desktop graphics performance 的本地化字符串。
        /// </summary>
        public static string GraphicsItem {
            get {
                return ResourceManager.GetString("GraphicsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 learn system assessment 的本地化字符串。
        /// </summary>
        public static string LearnSystemAssessment {
            get {
                return ResourceManager.GetString("LearnSystemAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Based on the lowest sub score 的本地化字符串。
        /// </summary>
        public static string LowestSubScore {
            get {
                return ResourceManager.GetString("LowestSubScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory(RAM) 的本地化字符串。
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Memory operations per second 的本地化字符串。
        /// </summary>
        public static string MemoryItem {
            get {
                return ResourceManager.GetString("MemoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open assessment log folder 的本地化字符串。
        /// </summary>
        public static string OpenAssessmentLogFolder {
            get {
                return ResourceManager.GetString("OpenAssessmentLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation 的本地化字符串。
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Primary disk 的本地化字符串。
        /// </summary>
        public static string PrimaryDisk {
            get {
                return ResourceManager.GetString("PrimaryDisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disk data transfer rate 的本地化字符串。
        /// </summary>
        public static string PrimaryDiskItem {
            get {
                return ResourceManager.GetString("PrimaryDiskItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Processor 的本地化字符串。
        /// </summary>
        public static string Processor {
            get {
                return ResourceManager.GetString("Processor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calculations per speed 的本地化字符串。
        /// </summary>
        public static string ProcessorItem {
            get {
                return ResourceManager.GetString("ProcessorItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run assessment 的本地化字符串。
        /// </summary>
        public static string RunAssessment {
            get {
                return ResourceManager.GetString("RunAssessment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sub score 的本地化字符串。
        /// </summary>
        public static string SubScore {
            get {
                return ResourceManager.GetString("SubScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your score is the latest, last updated: {0} 的本地化字符串。
        /// </summary>
        public static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tips 的本地化字符串。
        /// </summary>
        public static string Tips {
            get {
                return ResourceManager.GetString("Tips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1.It may take a few minutes to run the assessment. The screen may blink during the scoring process. 的本地化字符串。
        /// </summary>
        public static string TipsContent1 {
            get {
                return ResourceManager.GetString("TipsContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2.During the operation evaluation, a large amount of device resources will be occupied for a short period of time. During this period, the device may stall. Therefore, you are advised not to perform operations during this period. After the assesement is complete, the device returns to normal. 的本地化字符串。
        /// </summary>
        public static string TipsContent2 {
            get {
                return ResourceManager.GetString("TipsContent2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Assessment 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows experience index 的本地化字符串。
        /// </summary>
        public static string WEI {
            get {
                return ResourceManager.GetString("WEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It may take a few minutes to run the assessment. The screen may blink during the scoring process. 的本地化字符串。
        /// </summary>
        public static string WEITipContent {
            get {
                return ResourceManager.GetString("WEITipContent", resourceCulture);
            }
        }
    }
}
