import "Models\About\ReferenceKeyValuePairModel.idl";

namespace FileRenamer
{
    [bindable]
    [default_interface]
    runtimeclass ReferenceViewModel 
    {
        ReferenceViewModel();
        
        Windows.Foundation.Collections.IVector<ReferenceKeyValuePairModel> ReferenceDict{ get; };
    }
}
