namespace FileRenamer
{
    runtimeclass ThemeModel 
    {
        ThemeModel(String displayName , String internalName);

        String DisplayName{ get; set; };
        String InternalName{ get; set; };
    }
}
