namespace FileRenamerShellExtension
{
	unsealed runtimeclass BaseExplorerCommand
	{
		BaseExplorerCommand();
		Windows.Foundation.Collections.IVectorView<BaseExplorerCommand> SubCommands{ get; };
	}

	[default_interface]
	runtimeclass FileRenamerCommand : BaseExplorerCommand
	{
		FileRenamerCommand();
	}

	[default_interface]
	runtimeclass FileNameCommand : BaseExplorerCommand
	{
		FileNameCommand();
	}

	[default_interface]
	runtimeclass ExtensionNameCommand : BaseExplorerCommand
	{
		ExtensionNameCommand();
	}

	[default_interface]
	runtimeclass UpperAndLowerCaseCommand : BaseExplorerCommand
	{
		UpperAndLowerCaseCommand();
	}

	[default_interface]
	runtimeclass FilePropertiesCommand : BaseExplorerCommand
	{
		FilePropertiesCommand();
	}
}