namespace WindowsTools.Extensions.DataType.Enums
{
    public enum OperationKind
    {
        GenerateTextEmpty = 0,
        GenerateBarCodeFailed = 1,
        GenerateQRCodeFailed = 2,
        ParsePhotoFailed = 3,
        ReadClipboardImageFailed = 4,
        DeleteFileFailed = 5,
        LanguageChange = 6,
        ListEmpty = 7,
        TextEmpty = 8,
        NoOperation = 9,
        CheckUpdate = 10,
        LogClean = 11,
        LoopbackSetResult = 12,
        TerminateProcess = 13,
        File = 14,
        IconExtract = 15,
        ThemeChangeSameTime = 16,
        SwitchThemeSaveResult = 17,
        SwitchThemeRestoreResult = 18,
        MenuTitleEmpty = 19,
        MenuDefaultIconPathEmpty = 20,
        MenuLightThemeIconPathEmpty = 21,
        MenuDarkThemeIconPathEmpty = 22,
        MenuProgramPathEmpty = 23,
        MenuMatchRuleEmpty = 24,
        ShellMenuNeedToRefreshData = 25,
        ContextMenuUpdate = 26,
        InsiderPreviewSettings = 27,
        AddDriverAllSuccessfully = 28,
        AddDriverPartialSuccessfully = 29,
        AddDriverFailed = 30,
        AddInstallDriverAllSuccessfully = 31,
        AddInstallDriverPartialSuccessfully = 32,
        AddInstallDriverFailed = 33,
        DeleteDriverAllSuccessfully = 34,
        DeleteDriverPartialSuccessfully = 35,
        DeleteDriverSuccessfully = 36,
        DeleteDriverFailed = 37,
        ForceDeleteDriverAllSuccessfully = 38,
        ForceDeleteDriverPartialSuccessfully = 39,
        ForceDeleteDriverSuccessfully = 40,
        ForceDeleteDriverFailed = 41,
        SelectDriverEmpty = 42,
        CleanUpdateHistory = 43,
    }
}
