namespace FileRenamer
{
    [bindable]
    [default_interface]
    runtimeclass AboutViewModel 
    {
        AboutViewModel();
                
        Windows.UI.Xaml.Input.ICommand CreateDesktopShortcutCommand{ get; };
        Windows.UI.Xaml.Input.ICommand PinToStartScreenCommand{ get; };
        Windows.UI.Xaml.Input.ICommand PinToTaskbarCommand{ get; };
        Windows.UI.Xaml.Input.ICommand ShowReleaseNotesCommand{ get; };
        Windows.UI.Xaml.Input.ICommand ShowLicenseCommand{ get; };
    }
}
