import "Models\Settings\Appearence\ThemeModel.idl";

namespace FileRenamer
{
    [bindable]
    [default_interface]
    runtimeclass SettingsViewModel 
    {
        SettingsViewModel();

        ThemeModel Theme{ get; set; };

        Windows.UI.Xaml.Input.ICommand RestartCommand{ get; };
        Windows.UI.Xaml.Input.ICommand SettingsColorCommand{ get; };
        Windows.UI.Xaml.Input.ICommand ThemeSelectCommand{ get; };
    }
}
