//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Strings.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 View app information 的本地化字符串。
        /// </summary>
        public static string AppInformation {
            get {
                return ResourceManager.GetString("AppInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open App settings 的本地化字符串。
        /// </summary>
        public static string AppSettings {
            get {
                return ResourceManager.GetString("AppSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application Version: {0} 的本地化字符串。
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Backdrop settings instructions 的本地化字符串。
        /// </summary>
        public static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows 10 (earlier than 22000) does not support mica backdrop 的本地化字符串。
        /// </summary>
        public static string BackdropDescription {
            get {
                return ResourceManager.GetString("BackdropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check Update 的本地化字符串。
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Developer: 的本地化字符串。
        /// </summary>
        public static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 @高怡飞 的本地化字符串。
        /// </summary>
        public static string DeveloperName {
            get {
                return ResourceManager.GetString("DeveloperName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to visit the Developer home page 的本地化字符串。
        /// </summary>
        public static string DeveloperNameToolTip {
            get {
                return ResourceManager.GetString("DeveloperNameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language setting insturctions 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The name of the Start menu app doesn&apos;t change with the app language setting. Find the app in settings and click the Repair button and the app name changes without clearing your app&apos;s data. 的本地化字符串。
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project home page 的本地化字符串。
        /// </summary>
        public static string ProjectHomePage {
            get {
                return ResourceManager.GetString("ProjectHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quick operation 的本地化字符串。
        /// </summary>
        public static string QuickOperation {
            get {
                return ResourceManager.GetString("QuickOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project references 的本地化字符串。
        /// </summary>
        public static string Reference {
            get {
                return ResourceManager.GetString("Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Project references (Sort by alphabetical order) 的本地化字符串。
        /// </summary>
        public static string ReferenceTitle {
            get {
                return ResourceManager.GetString("ReferenceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to learn about the referenced open source project 的本地化字符串。
        /// </summary>
        public static string ReferenceToolTip {
            get {
                return ResourceManager.GetString("ReferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send feedback 的本地化字符串。
        /// </summary>
        public static string SendFeedback {
            get {
                return ResourceManager.GetString("SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Setting options instructions 的本地化字符串。
        /// </summary>
        public static string SettingsHelp {
            get {
                return ResourceManager.GetString("SettingsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View system information 的本地化字符串。
        /// </summary>
        public static string SystemInformation {
            get {
                return ResourceManager.GetString("SystemInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks 的本地化字符串。
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks (Sort by alphabetical order) 的本地化字符串。
        /// </summary>
        public static string ThanksTitle {
            get {
                return ResourceManager.GetString("ThanksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click Learn about the thank-your&apos;s personal information 的本地化字符串。
        /// </summary>
        public static string ThanksToolTip {
            get {
                return ResourceManager.GetString("ThanksToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update and licensing 的本地化字符串。
        /// </summary>
        public static string UpdateAndLicensing {
            get {
                return ResourceManager.GetString("UpdateAndLicensing", resourceCulture);
            }
        }
    }
}
