//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Strings.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Always show backdrop 的本地化字符串。
        /// </summary>
        public static string AlwaysShowBackdrop {
            get {
                return ResourceManager.GetString("AlwaysShowBackdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The window does not fall back to a solid color when it loses focus 的本地化字符串。
        /// </summary>
        public static string AlwaysShowBackdropDescription {
            get {
                return ResourceManager.GetString("AlwaysShowBackdropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Closed 的本地化字符串。
        /// </summary>
        public static string AlwaysShowBackdropOffContent {
            get {
                return ResourceManager.GetString("AlwaysShowBackdropOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Opened 的本地化字符串。
        /// </summary>
        public static string AlwaysShowBackdropOnContent {
            get {
                return ResourceManager.GetString("AlwaysShowBackdropOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Appearance 的本地化字符串。
        /// </summary>
        public static string Appearance {
            get {
                return ResourceManager.GetString("Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window background material 的本地化字符串。
        /// </summary>
        public static string Backdrop {
            get {
                return ResourceManager.GetString("Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acrylic 的本地化字符串。
        /// </summary>
        public static string BackdropAcrylic {
            get {
                return ResourceManager.GetString("BackdropAcrylic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        public static string BackdropDefault {
            get {
                return ResourceManager.GetString("BackdropDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sets the background color of the app&apos;s rendering 的本地化字符串。
        /// </summary>
        public static string BackdropDescription {
            get {
                return ResourceManager.GetString("BackdropDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica 的本地化字符串。
        /// </summary>
        public static string BackdropMica {
            get {
                return ResourceManager.GetString("BackdropMica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mica alt 的本地化字符串。
        /// </summary>
        public static string BackdropMicaAlt {
            get {
                return ResourceManager.GetString("BackdropMicaAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File right-click menu 的本地化字符串。
        /// </summary>
        public static string FileShellMenu {
            get {
                return ResourceManager.GetString("FileShellMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Whether to display the file right-click menu in the system 的本地化字符串。
        /// </summary>
        public static string FileShellMenuDescription {
            get {
                return ResourceManager.GetString("FileShellMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hide 的本地化字符串。
        /// </summary>
        public static string FileShellMenuOffContent {
            get {
                return ResourceManager.GetString("FileShellMenuOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show 的本地化字符串。
        /// </summary>
        public static string FileShellMenuOnContent {
            get {
                return ResourceManager.GetString("FileShellMenuOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Options 的本地化字符串。
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modify the language displayed in the app interface 的本地化字符串。
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart explorer 的本地化字符串。
        /// </summary>
        public static string RestartExplorer {
            get {
                return ResourceManager.GetString("RestartExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System backdrop settings 的本地化字符串。
        /// </summary>
        public static string SystemBackdropSettings {
            get {
                return ResourceManager.GetString("SystemBackdropSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System language settings 的本地化字符串。
        /// </summary>
        public static string SystemLanguageSettings {
            get {
                return ResourceManager.GetString("SystemLanguageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System theme settings 的本地化字符串。
        /// </summary>
        public static string SystemThemeSettings {
            get {
                return ResourceManager.GetString("SystemThemeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dark 的本地化字符串。
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Windows default 的本地化字符串。
        /// </summary>
        public static string ThemeDefault {
            get {
                return ResourceManager.GetString("ThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application theme 的本地化字符串。
        /// </summary>
        public static string ThemeMode {
            get {
                return ResourceManager.GetString("ThemeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the application theme to display 的本地化字符串。
        /// </summary>
        public static string ThemeModeDescription {
            get {
                return ResourceManager.GetString("ThemeModeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Window set on top 的本地化字符串。
        /// </summary>
        public static string TopMost {
            get {
                return ResourceManager.GetString("TopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Places the currently applied window at the very top 的本地化字符串。
        /// </summary>
        public static string TopMostDescription {
            get {
                return ResourceManager.GetString("TopMostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not pinned 的本地化字符串。
        /// </summary>
        public static string TopMostOffContent {
            get {
                return ResourceManager.GetString("TopMostOffContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pinned 的本地化字符串。
        /// </summary>
        public static string TopMostOnContent {
            get {
                return ResourceManager.GetString("TopMostOnContent", resourceCulture);
            }
        }
    }
}
