//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRenamer.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Window {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Window() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileRenamer.Strings.Window", typeof(Window).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FileRenamer 的本地化字符串。
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create desktop shortcut 的本地化字符串。
        /// </summary>
        public static string CreateDesktopShortcut {
            get {
                return ResourceManager.GetString("CreateDesktopShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create a shortcut to this app on your desktop 的本地化字符串。
        /// </summary>
        public static string CreateDesktopShortcutToolTip {
            get {
                return ResourceManager.GetString("CreateDesktopShortcutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Extension Name 的本地化字符串。
        /// </summary>
        public static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Name 的本地化字符串。
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Properties 的本地化字符串。
        /// </summary>
        public static string FileProperties {
            get {
                return ResourceManager.GetString("FileProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Maximize 的本地化字符串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Move 的本地化字符串。
        /// </summary>
        public static string Move {
            get {
                return ResourceManager.GetString("Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page {0} navigation failed 的本地化字符串。
        /// </summary>
        public static string NavigationFailed {
            get {
                return ResourceManager.GetString("NavigationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Others 的本地化字符串。
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Other options 的本地化字符串。
        /// </summary>
        public static string OthersToolTip {
            get {
                return ResourceManager.GetString("OthersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin to the Start screen 的本地化字符串。
        /// </summary>
        public static string PinToStartScreen {
            get {
                return ResourceManager.GetString("PinToStartScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin the app to Start screen 的本地化字符串。
        /// </summary>
        public static string PinToStartScreenToolTip {
            get {
                return ResourceManager.GetString("PinToStartScreenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin to taskbar 的本地化字符串。
        /// </summary>
        public static string PinToTaskbar {
            get {
                return ResourceManager.GetString("PinToTaskbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pin the app to taskbar 的本地化字符串。
        /// </summary>
        public static string PinToTaskbarToolTip {
            get {
                return ResourceManager.GetString("PinToTaskbarToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Application restart 的本地化字符串。
        /// </summary>
        public static string RestartApp {
            get {
                return ResourceManager.GetString("RestartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After the app settings are modified, some options need to be restarted to take effect 的本地化字符串。
        /// </summary>
        public static string RestartAppToolTip {
            get {
                return ResourceManager.GetString("RestartAppToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restore 的本地化字符串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings instruction 的本地化字符串。
        /// </summary>
        public static string SettingsInstruction {
            get {
                return ResourceManager.GetString("SettingsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show License 的本地化字符串。
        /// </summary>
        public static string ShowLicense {
            get {
                return ResourceManager.GetString("ShowLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View the app&apos;s license agreement 的本地化字符串。
        /// </summary>
        public static string ShowLicenseToolTip {
            get {
                return ResourceManager.GetString("ShowLicenseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show release notes 的本地化字符串。
        /// </summary>
        public static string ShowReleaseNotes {
            get {
                return ResourceManager.GetString("ShowReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Learn about app-specific updates 的本地化字符串。
        /// </summary>
        public static string ShowReleaseNotesToolTip {
            get {
                return ResourceManager.GetString("ShowReleaseNotesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size 的本地化字符串。
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upper and Lower Case 的本地化字符串。
        /// </summary>
        public static string UpperAndLowerCase {
            get {
                return ResourceManager.GetString("UpperAndLowerCase", resourceCulture);
            }
        }
    }
}
